title: AegisOps AI Engineering Blog
description: Engineering a Human-Supervised Crisis Decision Platform
theme: minima
markdown: kramdown

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: aegis
